### ISSUE TITLE
wazuh fork of ossec-hids is missing

### ISSUE THREAD

**Issue by ancientant** [wazuh/documentation#1]
Hi there, we notice that we can't clone https://github.com/wazuh/ossec-hids.git as the documentation directs.  It appears to be missing.

**Comment by santiago-bassett** [comment]
Hi ancientant, we are finalizing the documentation and plan to publish all repositories this Monday. Please check it out then and let us know if you have questions. We also appreciate contributions. Thank you!

**Comment by ancientant** [comment]
Sounds great!

**Comment by santiago-bassett** [comment]
Hi ancientant, last weekend we finally released our code and published all our repos. We also changed our website. Please have a look at it and give us your feedback. Don't hesitate to ask if you have questions.
